AllCops:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "features/support/env.rb"
    - "lib/tasks/cucumber.rake"
    - "script/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "vendor/**/*"

Documentation:
  Enabled: false

Rails:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# Decision based on the following
#https://github.com/bbatsov/rubocop/issues/3284
Style/FrozenStringLiteralComment:
  Enabled: false

# Decision based on the following
# https://github.com/bbatsov/rubocop/issues/3629
Rails/HttpPositionalArguments:
  Enabled: false