AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/test_helper.rb'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
