AllCops:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "features/support/env.rb"
    - "lib/tasks/cucumber.rake"
    - "script/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "vendor/**/*"

Documentation:
  Enabled: false

Rails:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
