sudo: required

language: ruby

services:
- docker

env:
  global:
  - secure: RDFuxL4dDfJETwPRlSyW9sWafISAP35pOqM6uvDeDgO1F1YSssu2IO5avmqAtM1QaVOJTL10oPQyJj4eOZjVwtVJMDGeQ8gllTtOCqr2UX9XkAzFS9JFLBXCqY2+WH+Dn/a/yANBI7wENDZWHNUfDcqZyhkK7AcejKGekp6GXaJJeFx6uDIkq2FKKrjWsDZ/x9NS7dM5WjSro1Z/L3HOoAoBqz13sCYbzUbjEklPfAHVUwQpHnWypg0IIwIo1TAfdUOv4r6eJqjwaYjc/FVMzKpc46H22q2fLY07/yCcQsT/uaIEtih7buhqugvSZltIRhi1V4MbHgQl6c7L2fEqJpG/nHFc68yEEp8arTiaKK+zIb4EvnNgniCwc8VcFkvx8FBnQsI3+VHIbg9OIFO7OMFr7EJMJ3cqM+lZ6sh2221Qm+VQT3Y2AAC8FnJCRyzc0u1ixwdDEZdOrsN3Yi/xsBZ0NUASe40allA2fM+ovhHL8T8HpW7bad+0ZpprLG6oXjVcLPth2sjT6kiWM3BhA5l10MGd0v8QwzAUQaSfAgqX/iSn2Aat2rPmDCySeqSADv5pYmhHI1OB6B7i7y1+igVoQSYF3VleNSf1XWHRvXwKKWFSpyEkLb6lnD9QTy1q3ux8MKT0RwDmhwFzJuXYqCz8piLRqKE5XwgsDJwCaWc=
  - secure: nGx5T6dDrzYQinYEIrAl8Okj9QkJ7hDQBA7iMKY49gB9jxPL/Sf04dkYjgP00sTpfpFhCadEtLf4C3J2r1j8/nXLHWGg7zdXNuQ2gXPvkLSplx0WthGG8lKvuwRc8h6ELWIHuqsCZ/r4vAHEXdLhCAoDIPqtwwcveDML/2TdUpRtBsz2gPL3pM7TU5rTh17U41Mh+/VHgyjdzA9RzzO0S3JsokGVNNK7d81kM1gP0K6byKAsO9Ij/hQDCcfHq/yHjin/rr36JKMTdCM9PD1sNfigOj712LPJGUo6wPcsv/+lc5VZG4Ili4F3nGBzxyT180Eq2lM+n4bkzSE67AXtDHbMmmjOKBSx48qNw9scnEWmfGe51b8JvTMdmNy1ZonfGVZapV/QTLyNhYBVh6FUqvTMI6bdhxnPNDM20LPRCYCowAQU1r9CzSf4GFKFSy4SQb2hB5Y/T4C12AoOGtggz0tiYrgBNUDoqcFeznG9CJmieXPHcWdOl8mNizSvYv2bs/I0/CrAI875lOqoYoY/yz1acqZG9gtd9kCD8ifvFKxP8IoAqBNA7kmvcVjdpx5fmDmlXrgkq8k8iop24OXOGFIAEXmSXvF1/Bxj/H6tSOqDg4llQM8De4kpbh7ASLWLS71lKqB28afTKozO4bmJD+cU8xXNRRG3628t0L/v0JY=
  - secure: wBbSM80IUz3hE2raKgHXFQZvC61wqrvtOlRvg5NKxG0nvCmobVoDfMGHNCn3FxS7uCTe4WoFPYecXXCec6loIz62JAEl7C+irEx3MyTOp29+r+9dKYXTIxV79QjbnTLDp5YJnXl+UdqHgVIaPf+nPJa9EZlxHjgwsDAP6jozrx9l3DO2P1MBs13Int8nXuz73+w0+Mdpg+3KuDLWE1uHNY+UrjsC6uPk5pxZqrrzjU5Xql7UtZIewL9wwhkL9txljD7AIGb0hnD5BPTdl9hamseYz/bSyvbq+VfuDf71ajtc9YRioF13PpV6eKgt/t/rwWGx0l/D7fXDcaLy1qOtkuavPn4lqcQGk1LRwyZrUips9KI/9GXAQGd8wUQ9tM80OHshbZADGkWkk2uXAMpmDsE174OdKV2LO7a4mpLL3vzEWBI6+8n7NJmxYtlr0fXj9b37xYULTYWz9rmpZG4QUOSS5/uIk9SQYXFYxObYFGzbGECIW9Wp/4NJ+UOtqNm7WHqrYJ0iOPAPVkm+DHuNCWrLipRmQmXFF1EFCsXcnYxWS0nZuFTjGN9xPiFMdbyRDtkdZF+mlM3mEbtxYg/p9Lsj9OaImPfu0qY0V4NrSrR63JO/totT771KhuxerOsSQYK3iVQJis2ARpas4CJOyCKk4Y9687nwA43XEvotLr4=
  - secure: bv6NUhInvBZ3M+hLrhAjDPbkBuQK4DNamD7ORHU/mj6zXWDgpEwae0+grDmIT5s7Bn5YaVESIsRTTUfDA8IKHb1Cd3zrkALLnAl8I1mzP2/wbj/X1ZRpYTPgtOAvf1n5bvxLS9N0zwQOGsnipATKFNvzS3MAowV60e8CSPOfiZg1yVoEFPHWXbZOgcKHo5Edycmv4YQv2AMZYW+tGate5/oZwCrjjT7/nxfOH0i9WEeXwkkk2npq2oCuk/l9YCS+xSPEoT1L8eJ4+sIZiYOhMbo8I8hfRynyoUxjbnlCZGG+Deq65oL4mONSp8ZPDBO1cTRVnasnyJQ+p2NT/ueMzFwzFy3Ba48PM66B6XsYDAFDniWsGI5/KNhMvrYhc4wnoYvCk7CSEpPkLaKRwFyPpqgTCzlChJ+ojWEJhLutOX6UPQM3rwbwvLNQCLRFK8dn6abQmHPkIFA48NL7ISJihLsWhKUVWGL7rGXcf3LCYpSpdkxZjkKVZ9mhMQ9iv6tIAo0mUkFfdYpOJ0wyMKFSiFESfHf7J5Gpf4LU5PXI7k8e10VTMLM/97JNdYI+jTH9VnM3TgTpDgT1W/hIWRO7tfjW2pMbI0fkmsHnc4Gy/ZkK2849lavnE3coUbuj5v8Gkgrmf94N1U6hVzPLMA/r/q4zz2zr8HNq2FyxRv4Rbj0=
  - DOCKER_VERSION=${TRAVIS_COMMIT}

cache:
- bundler

before_script:
- cp config/database.yml.travis config/database.yml
- bin/setup RAILS_ENV=test

script:
- bin/test

deploy:
  provider: script
  script: scripts/deploy_to_docker_hub.sh
  on:
    branch: master
