language: ruby
rvm:
  - 2.3.0
script:
  - bin/rubocop
  - bin/rspec --color --format documentation
  - bin/cucumber
before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/setup RAILS_ENV=test
