language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec rspec --color --format documentation
  - bundle exec rubocop
before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/setup RAILS_ENV=test
