db:
  image: postgres

app:
  build: .
  command: bin/rails s -p 3000 -b "0.0.0.0"
  volumes:
    - .:/srv/app
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    DATABASE_URL: postgres://postgres@db
  env_file: .env
