# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  encoding: unicode
  database: work-you-could-do_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: work-you-could-do_test

production:
  <<: *default
  database: work-you-could-do_production
