# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08797b8e21b5260a9c775d9180b47433199f1fc79182d167c246f33a9f1114ef3b0c1df3a511f9b47b0374f35b56d42651262dca64643bd69bfa71b70a9661d5
  lmi_secret_key: jtIbUmq6TjmYTFSk71HeBA==
  lmi_key_id: U9CMRK1DQSa5iX4N5wXrLQ==

test:
  secret_key_base: ad64f09b9437f0a7e0a440978bd5a928da013931f7ca17fcf37ec9f37177ff0760c447111f37ece4eccf02729b2e4cc1957556c42aac35c968622c12043fa4ba
  lmi_secret_key: jtIbUmq6TjmYTFSk71HeBA==
  lmi_key_id: U9CMRK1DQSa5iX4N5wXrLQ==

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  lmi_secret_key: <%= ENV["LMI_SECRET_KEY"] %>
  lmi_key_id: <%= ENV["LMI_KEY_ID"] %>
